version: '3.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: "host"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CREATE_TOPICS: "VideoEvents:1:1,TestEvents:1:1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"

  filebeat:
    build:
      context: filebeat/
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - type: bind
        source: ./logs
        target: /usr/share/filebeat/edx-logs
        read_only: true
    depends_on:
      - kafka
    network_mode: "host"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=docker-cluster
      - discovery.type=single-node
    network_mode: "host"
    volumes:
      - data03:/usr/share/elasticsearch/data:rw

volumes:
  data03:
    driver: local