filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/edx-logs/*.log

output.kafka:
  hosts: ["kafka:9092"]
  topic: "Generated"
  partition.round_robin:
    reachable_only: false
  version: '1.1.0'
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000